# Generated by Django 4.0.5 on 2022-06-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='term',
            field=models.TextField(null=True),
        ),
    ]
